//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.24 at 09:31:40 PM CEST 
//
/*
 * Copyright (C) 2006, 2007 Hewlett-Packard Development Company, L.P.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 ** Copyright (C) 2006, 2007 Hewlett-Packard Development Company, L.P.
 **  
 ** Authors: Simeon Pinder (simeon.pinder@hp.com), Denis Rachal (denis.rachal@hp.com), 
 ** Nancy Beers (nancy.beers@hp.com), William Reichardt 
 **
 **$Log: ResourceHandlersType.java,v $
 **Revision 1.2  2007/05/31 19:47:46  nbeers
 **Add HP copyright header
 **
 ** 
 *
 * $Id: ResourceHandlersType.java,v 1.2 2007/05/31 19:47:46 nbeers Exp $
 */


package net.java.dev.wiseman.server.handler.config._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import net.java.dev.wiseman.server.handler.config._1.ResourceHandlersType.ResourceHandler;


/**
 * <p>Java class for ResourceHandlersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceHandlersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resource-handler" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="resource-pattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="resource-handler-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceHandlersType", propOrder = {
    "resourceHandler"
})
public class ResourceHandlersType {

    @XmlElement(name = "resource-handler", namespace = "http://wiseman.dev.java.net/server/handler/config/1/resource-handler-config.xsd", required = true)
    protected List<ResourceHandler> resourceHandler;

    /**
     * Gets the value of the resourceHandler property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceHandler property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceHandler().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceHandler }
     * 
     * 
     */
    public List<ResourceHandler> getResourceHandler() {
        if (resourceHandler == null) {
            resourceHandler = new ArrayList<ResourceHandler>();
        }
        return this.resourceHandler;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="resource-pattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="resource-handler-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "resourcePattern",
        "resourceHandlerClass"
    })
    public static class ResourceHandler {

        @XmlElement(name = "resource-pattern", namespace = "http://wiseman.dev.java.net/server/handler/config/1/resource-handler-config.xsd", required = true)
        protected String resourcePattern;
        @XmlElement(name = "resource-handler-class", namespace = "http://wiseman.dev.java.net/server/handler/config/1/resource-handler-config.xsd", required = true)
        protected String resourceHandlerClass;

        /**
         * Gets the value of the resourcePattern property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResourcePattern() {
            return resourcePattern;
        }

        /**
         * Sets the value of the resourcePattern property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResourcePattern(String value) {
            this.resourcePattern = value;
        }

        /**
         * Gets the value of the resourceHandlerClass property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResourceHandlerClass() {
            return resourceHandlerClass;
        }

        /**
         * Sets the value of the resourceHandlerClass property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResourceHandlerClass(String value) {
            this.resourceHandlerClass = value;
        }

    }

}
