//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-382 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.29 at 01:59:34 PM EDT 
//

package org.xmlsoap.schemas.ws._2004._09.mex;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;any/>
 *         &lt;element ref="{http://schemas.xmlsoap.org/ws/2004/09/mex}MetadataReference"/>
 *         &lt;element ref="{http://schemas.xmlsoap.org/ws/2004/09/mex}Location"/>
 *       &lt;/choice>
 *       &lt;attribute name="Dialect" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="Identifier" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "any", "metadataReference", "location" })
@XmlRootElement(name = "MetadataSection")
public class MetadataSection {

    @XmlAnyElement(lax = true)
    protected Object any;
    @XmlElement(name = "MetadataReference")
    protected MetadataReference metadataReference;
    @XmlElement(name = "Location")
    @XmlSchemaType(name = "anyURI")
    protected String location;
    @XmlAttribute(name = "Dialect", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String dialect;
    @XmlAttribute(name = "Identifier")
    @XmlSchemaType(name = "anyURI")
    protected String identifier;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();


    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Object } {@link Element }
     * 
     */
    public Object getAny() {
        return any;
    }


    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Object } {@link Element }
     * 
     */
    public void setAny(Object value) {
        this.any = value;
    }


    /**
     * Gets the value of the metadataReference property.
     * 
     * @return possible object is {@link MetadataReference }
     * 
     */
    public MetadataReference getMetadataReference() {
        return metadataReference;
    }


    /**
     * Sets the value of the metadataReference property.
     * 
     * @param value allowed object is {@link MetadataReference }
     * 
     */
    public void setMetadataReference(MetadataReference value) {
        this.metadataReference = value;
    }


    /**
     * Gets the value of the location property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocation() {
        return location;
    }


    /**
     * Sets the value of the location property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLocation(String value) {
        this.location = value;
    }


    /**
     * Gets the value of the dialect property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDialect() {
        return dialect;
    }


    /**
     * Sets the value of the dialect property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDialect(String value) {
        this.dialect = value;
    }


    /**
     * Gets the value of the identifier property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdentifier() {
        return identifier;
    }


    /**
     * Sets the value of the identifier property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }


    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
