//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-382 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.29 at 01:59:34 PM EDT 
//

package net.java.dev.wiseman.schemas.metadata.messagetypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for OperationNodeType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationNodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="input" type="{http://schemas.wiseman.dev.java.net/metadata/messagetypes}InputType"/>
 *         &lt;element name="output" type="{http://schemas.wiseman.dev.java.net/metadata/messagetypes}OutputType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationNodeType", propOrder = { "input", "output" })
public class OperationNodeType {

    @XmlElement(required = true)
    protected InputType input;
    @XmlElement(required = true)
    protected OutputType output;
    @XmlAttribute(required = true)
    protected String name;


    /**
     * Gets the value of the input property.
     * 
     * @return possible object is {@link InputType }
     * 
     */
    public InputType getInput() {
        return input;
    }


    /**
     * Sets the value of the input property.
     * 
     * @param value allowed object is {@link InputType }
     * 
     */
    public void setInput(InputType value) {
        this.input = value;
    }


    /**
     * Gets the value of the output property.
     * 
     * @return possible object is {@link OutputType }
     * 
     */
    public OutputType getOutput() {
        return output;
    }


    /**
     * Sets the value of the output property.
     * 
     * @param value allowed object is {@link OutputType }
     * 
     */
    public void setOutput(OutputType value) {
        this.output = value;
    }


    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
        return name;
    }


    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }

}
