//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-382 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.29 at 01:59:34 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.wiseman.dev.java.net/metadata/messagetypes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.java.dev.wiseman.schemas.metadata.messagetypes;
